### ISSUE TITLE
Execution error: ModuleNotFoundError: No module named 'clinv'

### ISSUE THREAD

**Issue by scott-dunt** [lyz-code/clinv#36]

**Comment by lyz-code** [comment]
Hi @scott-dunt , sorry I just saw your issue, what's the bug/feature you're trying to report?

**Comment by scott-dunt** [comment]
sorry, I gave up on it and went with a different tool. but on Ubuntu 20.04 after following the install doc, it won't run, although pip3 thinks its ok:

pip3 check clinv
No broken requirements found.

:~/Programs/AWS/clinv$ clinv
Traceback (most recent call last):
  File "/usr/local/bin/clinv", line 11, in <module>
    load_entry_point('clinv==0.9.0', 'console_scripts', 'clinv')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'clinv'

**Comment by lyz-code** [comment]
It looks like the last build is broken :(. Thanks for the report,

While I fix it you can try the fix/installation branch which now installs correctly

**Comment by lyz-code** [comment]
This has been fixed in `1.0.0`, sorry for the implementation delay :(
